#ifndef SL_DEVICE_INIT_HFRCO_CONFIG_H
#define SL_DEVICE_INIT_HFRCO_CONFIG_H

// <<< Use Configuration Wizard in Context Menu >>>

// <o SL_DEVICE_INIT_HFRCO_BAND> Frequency Band
// <i> RC Oscillator Frequency Band
// <cmuHFRCODPLLFreq_1M0Hz=> 1 MHz
// <cmuHFRCODPLLFreq_2M0Hz=> 2 MHz
// <cmuHFRCODPLLFreq_4M0Hz=> 4 MHz
// <cmuHFRCODPLLFreq_7M0Hz=> 7 MHz
// <cmuHFRCODPLLFreq_13M0Hz=> 13 MHz
// <cmuHFRCODPLLFreq_16M0Hz=> 16 MHz
// <cmuHFRCODPLLFreq_19M0Hz=> 19 MHz
// <cmuHFRCODPLLFreq_26M0Hz=> 26 MHz
// <cmuHFRCODPLLFreq_32M0Hz=> 32 MHz
// <cmuHFRCODPLLFreq_38M0Hz=> 38 MHz
// <cmuHFRCODPLLFreq_48M0Hz=> 48 MHz
// <cmuHFRCODPLLFreq_56M0Hz=> 56 MHz
// <cmuHFRCODPLLFreq_64M0Hz=> 64 MHz
// <cmuHFRCODPLLFreq_80M0Hz=> 80 MHz
// <i> Default: cmuHFRCODPLLFreq_80M0Hz


#ifndef MLTK_CPU_CLOCK
#error Must add command-line #define MLTK_CPU_CLOCK
#endif

// #define SL_DEVICE_INIT_HFRCO_BAND           cmuHFRCODPLLFreq_80M0Hz

#if MLTK_CPU_CLOCK == 80000000
#define SL_DEVICE_INIT_HFRCO_BAND  cmuHFRCODPLLFreq_80M0Hz
#elif MLTK_CPU_CLOCK == 64000000
#define SL_DEVICE_INIT_HFRCO_BAND  cmuHFRCODPLLFreq_64M0Hz
#elif MLTK_CPU_CLOCK == 56000000
#define SL_DEVICE_INIT_HFRCO_BAND  cmuHFRCODPLLFreq_56M0Hz
#elif MLTK_CPU_CLOCK == 48000000
#define SL_DEVICE_INIT_HFRCO_BAND  cmuHFRCODPLLFreq_48M0Hz
#elif MLTK_CPU_CLOCK == 38000000
#define SL_DEVICE_INIT_HFRCO_BAND  cmuHFRCODPLLFreq_38M0Hz
#elif MLTK_CPU_CLOCK == 32000000
#define SL_DEVICE_INIT_HFRCO_BAND  cmuHFRCODPLLFreq_32M0Hz
#elif MLTK_CPU_CLOCK == 26000000
#define SL_DEVICE_INIT_HFRCO_BAND  cmuHFRCODPLLFreq_26M0Hz
#elif MLTK_CPU_CLOCK == 19000000
#define SL_DEVICE_INIT_HFRCO_BAND  cmuHFRCODPLLFreq_19M0Hz
#elif MLTK_CPU_CLOCK == 16000000
#define SL_DEVICE_INIT_HFRCO_BAND  cmuHFRCODPLLFreq_16M0Hz
#elif MLTK_CPU_CLOCK == 13000000
#define SL_DEVICE_INIT_HFRCO_BAND  cmuHFRCODPLLFreq_13M0Hz
#elif MLTK_CPU_CLOCK == 7000000
#define SL_DEVICE_INIT_HFRCO_BAND  cmuHFRCODPLLFreq_7M0Hz
#elif MLTK_CPU_CLOCK == 4000000
#define SL_DEVICE_INIT_HFRCO_BAND  cmuHFRCODPLLFreq_5M0Hz
#elif MLTK_CPU_CLOCK == 2000000
#define SL_DEVICE_INIT_HFRCO_BAND  cmuHFRCODPLLFreq_2M0Hz
#elif MLTK_CPU_CLOCK == 1000000
#define SL_DEVICE_INIT_HFRCO_BAND  cmuHFRCODPLLFreq_1M0Hz
#else
#error Invalid MLTK_CPU_CLOCK, must be 80M,64M,56M,48M,38M,32M,26M,19M,16M,13M,7M,4M,2M,or 1M
#endif

// <<< end of configuration section >>>

#endif // SL_DEVICE_INIT_HFRCO_CONFIG_H
